sudo: required

language: generic

services:
  - docker

env:
  global:
    - HOME_BUILD=$HOME/build
    - ROS2WS=$HOME_BUILD/ros2_java_ws

before_install:
- docker pull theosakamg7/ros2java:latest
- echo "INSTALL/BUILD ROS2 AMENT..."
- cd $HOME_BUILD && mkdir -p ament_ws/src && cd $HOME_BUILD/ament_ws
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/wget https://gist.githubusercontent.com/Theosakamg/e6084cfafa6b7ea690104424cef970a2/raw/ament_java.repos"
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/vcs import src < ament_java.repos"
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "src/ament/ament_tools/scripts/ament.py build --symlink-install --isolated"
- echo "INSTALL ROS2 WS..."
- cd $HOME_BUILD && mkdir -p $ROS2WS/src && cd $ROS2WS
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/wget https://gist.githubusercontent.com/Theosakamg/d9259bbc708c5145255fbdeb25e65e19/raw/ros2_java_desktop.repos"
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/vcs import src < ros2_java_desktop.repos"
- cd $ROS2WS/src/ros2/rosidl_typesupport && patch -p1 < ../../ros2_java/ros2_java/rosidl_ros2_java.diff
- cd $ROS2WS/src/eProsima/Fast-RTPS && git submodule init && git submodule update
- rm -rf $ROS2WS/src/ros2_java/ros2_java_utils && ln -s $HOME_BUILD/ros2java-alfred/ros2_java_utils $ROS2WS/src/ros2_java/ros2_java_utils
- echo "BUILD ROS2 WS..."
- cd $HOME_BUILD && ls -lFa ./ && find . -maxdepth 3 -type d -not \( -path "./.git" -prune \)
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN -w `pwd` theosakamg7/ros2java:latest sh -c ". ament_ws/install_isolated/local_setup.sh && cd /home/travis/build/ros2_java_ws && ament build --symlink-install --isolated --skip-packages $PKG_EXCLUDE"

script:
- cd $HOME_BUILD && docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c ". ament_ws/install_isolated/local_setup.sh && cd /home/travis/build/ros2_java_ws && ament test --isolated --only rcljava_utils"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4aac82b42245203edceb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
